### ISSUE TITLE
Shizuku can't start via root shell

### ISSUE THREAD

**Issue by NSTAdventure** [RikkaApps/Shizuku#154]
I don't know why but shizuku can't start the server via root shell
I use latest one v11 from f droid
And i use android version 7.1.2 rooted with supersu from chainfire

Any help? 🙏
[logcat_09-10-2021_22-05-23.txt](https://github.com/RikkaApps/Shizuku/files/7144331/logcat_09-10-2021_22-05-23.txt)

**Comment by RikkaW** [comment]
1. Use the latest version from GitHub release
2. Provide the log during the start process (You can use any logcat app, run `logcat` in terminal apps, or `adb logcat` if you have a computer, to catch the log)

**Comment by NSTAdventure** [comment]
> 1. Use the latest version from GitHub release
> 2. Provide the log during the start process (You can use any logcat app, run `logcat` in terminal apps, or `adb logcat` if you have a computer, to catch the log)

**Comment by RikkaW** [comment]
From the log, I can see you are running Shizuku in a virtual environment.

Virtual environment is NOT supported since anything could happen in those BS.

At the end of your log, I can even see Shizuku's process is using Fabric and Crashlytics. But you can see, Shizuku does not include 
Fabric or Crashlytics. Should question you if you download Shizuku from a random thirdparty? 

Thank you for wasting my time :)

You can open a new issue if are sure you download Shizuku from GitHub release and your problem still exists in a real enviroment :)

**Comment by NSTAdventure** [comment]
As use tbh i dislike stupid and any offensive words instead of saying like those kind of words just add invalid tag 👍

**Comment by RikkaW** [comment]
Root and ADB required software are usually closely associated with the Android system. For Shizuku, is even more closely associated. When you find a problem and want to report it to software developers, the first thing is to disable anything that would affect the software, especially the virtual environment and Xposed, and try if the problem still exists. 

But you don't tell this at all. I believe that no one would have a good feeling about this since you are doing bad things first :)

**Comment by NSTAdventure** [comment]
> But you don't tell this at all. I believe that no one would have a good feeling about this since you are doing bad things first :)

Hi sorry for waste your time can you share what mistake that i have done? 🙏🤔

**Comment by RikkaW** [comment]
This is the third time I tell this:
You are running Shizuku in a virtual environment, and this virtual environment has Xposed bundled. Both of them could break any software, especially software like Shizuku that is closely associated with the Android system.

I don't expect you will disable them first, but at least you should tell that you are using a virtual environment and Xposed when you reporting your problem.

**Comment by NSTAdventure** [comment]
> This is **the third time** I tell this:
> **You are running Shizuku in a virtual environment, and this virtual environment has Xposed bundled. Both of them could break any software, especially software like Shizuku that is closely associated with the Android system.**
> 
> I don't expect you will disable them first, but at least you should tell that you are using a virtual environment and Xposed when you reporting your problem.

Oh yes okay forgive me for my mistake 🙏

Can u remove stupid label and add invalid label instead? 🙏

Thanks for everything 🙏

**Comment by haruue** [comment]
Nope, your mistake is never forgiven by us.
And if you don't stop posting these stupid issues, you will be banned from orgs/RikkaApps.
