### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by usr-canis** [RikkaApps/Shizuku#173]
Hi rikka
It would be nice if we can run shell commands directly from shizuku app itself without having to use a seperate terminal app 
Thanks❤️

**Comment by haruue** [comment]
A perfect terminal emulator is not as simple as you think. Even if we introduce it into Shizuku, this feature will become buggy, and waste much time to maintain, so why not just use those perfect terminal emulator applications?

We should always keep Shizuku [simple & graceful](https://wiki.archlinux.org/title/Arch_terminology#KISS), instead of making it bloat like Messenger or WeChat.
