### ISSUE TITLE
Shizuku won't autostart automaticaly with boot.

### ISSUE THREAD

**Issue by 1337-537h** [RikkaApps/Shizuku#206]
Please report bugs of Shizuku itself.

**Requirements:**

- [x] Shizuku version is up-to-date
- [x] Shizuku is downloaded from official channels (GitHub release or Google Play)
- [x] Shizuku is not running in a virtual environment
- [x] (Root users) No Xposed installed / Xposed is not enabled for Shizuku

Change "[ ]" to "[x]" if it meets the requirements.

**Reports not meet the requirements will be immediately closed**.

**Information:**

- Shizuku version:12.6.0.r762.6812764
- Mode: [adb, root] root
- Android version: 11
- Device: OP Nord 2 5G

In settings i enable Start on boot (root).
But when my device reboot the Shizuku won't start. I must press Start button to enable it manually.
If there is a bug i have tasker so if you can help me i can make it start via tasker, if not is there any solution to enable start on boot automaticaly?

**Comment by RikkaW** [comment]
Please make sure if this is not caused by battery optimization features from your device manufacturer (OnePlus).

**Comment by 1337-537h** [comment]
I just check it again.
Allow foreground activity is ON
Allow background activity is ON too.
Reboot the device and when i open shizuku i must press Start to start, wont do it automatically.

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Shizuku/blob/0f0de1254ce7454e9db8a71811301bab94bc0ba9/manager/src/main/java/moe/shizuku/manager/starter/BootCompleteReceiver.kt#L25

This log shows if the `BOOT_COMPLETED` or `LOCKED_BOOT_COMPLETED` broadcast is received. It looks like `I/ShizukuManager: start on boot, action=`

Every time an app is started, you will see a log from ActivityManager like `I/ActivityManager: Start proc`.

Combine these two types of logs, you can check if Shizuku is started by the system on boot, if the broadcast receiver from Shizuku app runs.

Since your device is rooted, you can use adb logcat, any logcat app you like or this tool (https://t.me/hzrtools/10) to catch log.

**Comment by 1337-537h** [comment]
What is Sui in magisk?
If i enable "Zygisk - Sui" as alternative can i uninstall the Shizuku?

**Comment by RikkaW** [comment]
No difference unless you are using super old apps that haven't support Sui.
