### ISSUE TITLE
Suggestion to notify user if shizuku stops running? 

### ISSUE THREAD

**Issue by spart0n654** [RikkaApps/Shizuku#234]

**Comment by RikkaW** [comment]
It's possible, and this requires Shizuku app not being killed (technically speaking, Shizuku app needs to run a foreground service that hold the `DeathRecipient` of the `Binder` of Shizuku server). However, on devices from Xiaomi, OnePlus, Samusng, etc., users need to tweak multiple options to keep Shizuku app alive. Also, we need to write another help document to teach the user how to do this.

I have had a user claiming he has read this section (["Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops"](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops)) of the document but Shizuku still randomly stops. I suggested him to try some steps in that section, he said that step works. So, I'm always curious if the real problem is the user refuses to read the help.

**Comment by spart0n654** [comment]
> It's possible, and this requires Shizuku app not being killed (technically speaking, Shizuku app needs to run a foreground service that hold the `DeathRecipient` of the `Binder` of Shizuku server). However, on devices from Xiaomi, OnePlus, Samusng, etc., users need to tweak multiple options to keep Shizuku app alive. Also, we need to write another help document to teach the user how to do this.
> 
> I have had a user claiming he has read this section (["Start via wireless debugging/Start by connecting to a computer: Shizuku randomly stops"](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging-start-by-connecting-to-a-computer-shizuku-randomly-stops)) of the document but Shizuku still randomly stops. I suggested him to try some steps in that section, he said that step works. So, I'm always curious if the real problem is the user refuses to read the help.

I have a feeling it's the app naptime by Franco here on XDA that I use. 
https://play.google.com/store/apps/details?id=com.franco.doze


But here lately after I've extremely debloated my Samsung and left it bare bones Google and some Samsung for my galaxy watch, it seems like it's not getting killed like at all now. But definitely an optional watchdog service could be a nice.

**Comment by RikkaW** [comment]
The thing that does the real work is not Shizuku app, it's Shizuku server, a process started by adb, which is not affected by battery optimization features. Keep Shizuku app alive is meaningless.

**Comment by spart0n654** [comment]
> The thing that does the real work is not Shizuku app, it's Shizuku server, a process started by adb, which is not affected by battery optimization features. Keep Shizuku app alive is meaningless.

Gotcha! That makes sense now! Okay yeah you can kill this request then nevermind lol

**Comment by RikkaW** [comment]
My point is if the user can read the help, they should not have the problem. If not, it's impossible to "notify user if shizuku stops running".

**Comment by e-t-l** [comment]
> My point is if the user can read the help, they should not have the problem. If not, it's impossible to "notify user if shizuku stops running".

In an ideal world, this is true. Unexpected errors can happen in any system, though. It would be nice if there were some easily-accessible way to confirm the server is running without having to open the app, like a quick settings tile or a (optional) persistent notification.
