### ISSUE TITLE
About the gradle plugin version in build.gradle

### ISSUE THREAD

**Issue by ppoffice** [RikkaApps/Shizuku#80]
Hi @RikkaW. I found that the gradle plugin version set in `build.gradle` is `4.2.0-alpha05`, which is incompatible with the latest release of Android Studio in the stable channel (4.0.1). Changing it to `4.0.1` resolve the issue for me. Considering the latest RC version of Android Studio is only `4.1 RC 1` as of August 2020 and not everyone is using RC or Canary, should we change the plugin to a previous version?

**Comment by RikkaW** [comment]
I have recently use prefab version BoringSSL to replace the "unreliable" dlopen&dlsym in https://github.com/RikkaApps/Shizuku/commit/bec37082e6c9f1daaadfc35d1afe6391e75ce626 (BoringSSL is used by Android 11's adb over TLS implementation). The prefab support is added from AGP 4.0, but it does not seem to work correctly (compile error). Since downgrade to AGP 4.1 still requires Android Studio 4.1 and having multiple versions of Android Studio installed side by side is possible and easy (such as via JetBrains Toolbox), I don't think we should change the AGP to a previous version.
